---
title: Exploring Python Through RStudio
author: Mika Oldham
date: '2020-05-12'
slug: exploring-python-through-rstudio
categories: []
tags: []
description: ''
---
There is a common debate among the coding world as to which language is better: R or Python. Though these languages are different and one might be preferable over the other in certain situations, there is actually a lot of overlap in the usage of R and Python. First, the python language can actually be ran and interpreted within the R-studio system. In the example below, the code is translated to Python despite bring run in R due to the specification of {python} at the beginning of the chunk:

```{python}
#Py chunk:
five_p=5
print(five_p)
two_p=2
print(two_p)
five_p**two_p
```

The same code from above in the Python chunk can be run below in the R chunk, but this time in the language of R:
```{R}
#R chunk:
five_r <- 5
five_r
two_r <- 2
two_r
five_r^(two_r)
```
Though different notations and different languages, both codes where able to be run in R and resulted in the same, correct answer.

So, both languages can be run in R, but what how do the functions within each language compare? Through slightly different notations, both R and Python can execute a lot of the same functions.

+ One resemblance is the "numpty" add-on in Python, which parallels a lot of the  arithmetic functions that come installed with R-studio. Numpty contains an abundance of pre-defined functions. Using R, we can execute basic functions such as:
```{R}
#R chunk:
#create a vector of 10 random numbers between 1 and 100 with replacement
set.seed(345)
vector <- sample(1:100, 10, replace=TRUE)
vector
#find the mean of the vector
mean_r <- mean(vector)
mean_r
#find the log of the mean
log_r <- log(mean_r)
log_r
```

The same functions from R can be executed using numpy in Python:
```{python}
import numpy as np
#create an array of 10 random numbers between 1 and 100 with replacement
array1=np.random.randint(low=1, high=100, size=10)
print(array1)
#to be consistent with the R code, replace the values with the randomly generated values from above by creating a new array
array2=np.array([93, 87, 83, 95, 21, 50, 60, 84, 28, 97])
print(array2)
#find the mean of the array
mean_p=np.mean(array2)
print(mean_p)
#find the log of the mean
log_p=np.log(mean_p)
print(log_p)
```
Even though the codes slightly differ, we still get the same results! Also, notice the difference in rounding between the R answers and the Python answers. In this case, it is evident that R truncates earlier than Python does, thereofre Python is showing more exact answers. 