<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Mika Oldham" />
    <meta name="description" content="A personal page displaying my resume, project accomplishments, and ways to contact me.">
    <link rel="shortcut icon" type="image/x-icon" href="/img/favicon.ico">
    <title>Project 2: Modeling, Testing, and Predicting Headache Status</title>
    <meta name="generator" content="Hugo 0.70.0" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">

      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="/blog/">BLOG</a></li>
        
        <li><a href="/projects/">PROJECTS</a></li>
        
        <li><a href="/oldham_mika_resume.pdf">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      
      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="/project2final/">Project 2: Modeling, Testing, and Predicting Headache Status</a></strong>
          </h3>
        </div>
        <div class="blog-title">
          <h4>
          January 1, 0001
            &nbsp;&nbsp;
            
          </h4>
        </div>
        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<p>###Introduction to the data:
The following data was pulled from a study by Tammy Kostecki-Dillon that was conducted on patients who suffered chronic headaches. The <strong>numeric variables</strong> include “id” which identifies each patient, “dos” which measures the time in days since the patient began participation in the study, “time” which measures the time in days since the onset of treatment during the study (with negative values representing the number of days before the onset of treatment), “age” which measures the age in years of the patient, and “airq” which measures the air quality index for that day with a higher air index representing worse air quality and a lower index representing better air quality. The first <strong>categorical variable</strong> is “hatype” which identifies the type of headache as being “aura” for a aura headache, “non-aura” for a headache that does not contain aura symptoms, or “mixed” for a headache that demonstrates some symptoms of a normal headache and some symptoms of an aura headache. The next categorical variable is “medication” which identifies the level of treatment through whether it is being “continued”, “reduced”, or “none” for stopped treatment. The last categorical variables are “headache” which identifies a day with a headahe as “yes” and a day without a headache as “no”, while “sex” represents whether the patient is “male” or “female”. There are a total of <strong>4152 observations</strong> in this data set.</p>
<p>As someone who frequently experiences symptoms of auras prior to a migraine, I found this data set to be really interesting! I was eager to see if there were any aspects that might predict the onset of auras, and the variables in the data provided a great opportunity to explore this through regressions. A glimpse of the data is shown below:</p>
<pre class="r"><code>headache &lt;- read.csv(&quot;https://vincentarelbundock.github.io/Rdatasets/csv/carData/KosteckiDillon.csv&quot;)
headache &lt;- headache %&gt;% select(-X)
head(headache)</code></pre>
<pre><code>##   id time dos hatype age airq medication headache    sex
## 1  1  -11 753   Aura  30    9 continuing      yes female
## 2  1  -10 754   Aura  30    7 continuing      yes female
## 3  1   -9 755   Aura  30   10 continuing      yes female
## 4  1   -8 756   Aura  30   13 continuing      yes female
## 5  1   -7 757   Aura  30   18 continuing      yes female
## 6  1   -6 758   Aura  30   19 continuing      yes female</code></pre>
<p>###MANOVA &amp; ANOVA
The following MANOVA test was conducted to determine if any considered numeric variable, age or airquality, had significantly different mean values for the different types of headaches: aura, non-aura, or mixed. This test could be important for further analysis testing if certain demographic factors, such as age or airquality in the city of residence, can cause people to have a predisposition for certain types of headaches.</p>
<p>First, the assumptions were checked:</p>
<ul>
<li>The tested data was from a <strong>random sample</strong> and the observations were <strong>independent</strong> <span class="math inline">\(\checkmark\)</span></li>
<li><strong>Multivariate Normality</strong>:</li>
</ul>
<pre class="r"><code>ggplot(headache, aes(x = age, y = airq)) + 
  geom_point(alpha=.5) + geom_density_2d(h=2) +
  coord_fixed() + facet_wrap(~hatype)</code></pre>
<p><img src="/project2final_files/figure-html/unnamed-chunk-2-1.png" width="768" style="display: block; margin: auto;" />
Based on these plots, there is no clear normality of the data in each group. Therefore, the assumption of multivariate normality is not met and we proceed with caution.</p>
<ul>
<li><strong>Homogeneity of within-group covariance matrices</strong>:</li>
</ul>
<pre class="r"><code>covariance &lt;- headache %&gt;% group_by(hatype) %&gt;% do(covs=cov(.[5:6]))
for(i in 1:3){print(as.character(covariance$hatype[i]))
print(covariance$covs[i])}</code></pre>
<pre><code>## [1] &quot;Aura&quot;
## [[1]]
##             age      airq
## age  129.408036 -3.205749
## airq  -3.205749 83.063081
## 
## [1] &quot;Mixed&quot;
## [[1]]
##             age      airq
## age  154.518926  5.285457
## airq   5.285457 50.556670
## 
## [1] &quot;No Aura&quot;
## [[1]]
##             age       airq
## age  108.879813  -4.513002
## airq  -4.513002 103.442276</code></pre>
<p>The covariance among all headache types appear to differ. The homogeneity of covariance assumption is not met so again, we proceed with caution.</p>
<p>After checking assumptions, the test was conducted.</p>
<ul>
<li><p>Ho: For both age and airquality, the means of the headache type groups are equal.</p></li>
<li><p>HA: For atleast one of the response variables, either age, airquality, or both, atleast 1 of the headache type means is different than the others.</p></li>
</ul>
<pre class="r"><code>man &lt;- manova(cbind(age, airq) ~ hatype, data=headache)
summary(man)</code></pre>
<pre><code>## Df Pillai approx F num Df den Df Pr(&gt;F)
## hatype 2 0.040322 42.684 4 8298 &lt; 2.2e-16 ***
## Residuals 4149
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<p>Based on these results, there is a significant difference among the headache types for atleast one of the dependent variables (p&lt;0.001).</p>
<p>Since the MANOVA results were significant, <strong>univariate ANOVA tests</strong> were run to see which dependent variable, age or airquality, had a significantly different mean value for atleast one of the headache types.</p>
<pre class="r"><code>summary.aov(man) </code></pre>
<pre><code>## Response age :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## hatype 2 13181 6590.3 53.864 &lt; 2.2e-16 ***
## Residuals 4149 507637 122.4
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response airq :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## hatype 2 5516 2758.13 30.909 4.738e-14 ***
## Residuals 4149 370238 89.24
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<p>The ANOVA results show that both age (p&lt;.001) and airquality (p&lt;.001) have significant mean differences for atleast one of the headache types. This was prior to adjusting the significance level based on the type 1 error rate, which will be discussed further below.</p>
<p>Since the ANOVA results were found to be significant, <strong>post-hoc analysis tests</strong> were conducted to determine which headache type had differing means for the age variable and for the airquality variable.</p>
<pre class="r"><code>headache %&gt;% group_by(hatype) %&gt;% summarize(mean(age), mean(airq))</code></pre>
<pre><code>## # A tibble: 3 x 3
##   hatype  `mean(age)` `mean(airq)`
##   &lt;chr&gt;         &lt;dbl&gt;        &lt;dbl&gt;
## 1 Aura           40.9         24.3
## 2 Mixed          40.0         22.4
## 3 No Aura        44.2         25.9</code></pre>
<pre class="r"><code>pairwise.t.test(headache$airq, headache$hatype, p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  headache$airq and headache$hatype 
## 
##         Aura    Mixed  
## Mixed   0.00012 -      
## No Aura 2.6e-07 7.6e-13
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(headache$age, headache$hatype, p.adj=&quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  headache$age and headache$hatype 
## 
##         Aura    Mixed  
## Mixed   0.12    -      
## No Aura &lt; 2e-16 1.9e-13
## 
## P value adjustment method: none</code></pre>
<p>According to the pairwise comparisons, all three headache types had significantly different mean values of airquality (p&lt;0.001). For the age variable, it was found that all headache types had different mean values (p&lt;.001) except for when comparing age values for “aura” headaches and “mixed” headaches (p=.12). Again, these significance comparison values were based on alpha=0.05, but adjusted significant levels are discussed below. The conclusion that “aura” and “mixed” groups do not have significantly different mean ages is consistent with the average values seen in the table above, as these two groups had average values both at about 40 years, while the “no aura” group had a higher average age of about 44 years. Likewise, the airquality conclusion of all different averages is supported by the fact that the “no aura” group had an average airquality of almost 26, the “aura” group had an average airquality of about 24, and the “mixed” group has an average airquality of about 22.</p>
<p>Next, the <strong>probability of Type I errors</strong> was recalculated because there were 9 hypothesis tests total (1 MANOVA, 2 ANOVA, and 6 pairwise t-tests). Because the probability of executing a Type I error increases with each comparison, and there were 9 tests conducted above, the probability was corrected by:</p>
<pre class="r"><code>#P(type l error):
1-((.95)^9)</code></pre>
<pre><code>## [1] 0.3697506</code></pre>
<p>The corrected probablity of a Type 1 error, based on the 9 hypothesis tests that were conducted, ends up being 0.3698. This is higher than the normal error rate we see with one test, which is 0.05, because each individual test has the 0.05 error rate.</p>
<p>To account for this increase in probability of Type 1 error due to repeated hypothesis tests, the <strong>Bonferroni correction</strong> was applied. The new alpha-p-value used for significance comparisons was calculated by:</p>
<pre class="r"><code>#Bonferroni corrected alpha:
.05/9</code></pre>
<pre><code>## [1] 0.005555556</code></pre>
<p>By dividing the alpha value for one test by the number of tests conducted, the new alpha value used for comparisons is .00556. This means that by comparing test p-values to this corrected alpha-p-value, we keep the overall Type I error rate at .05. When using this Bonferroni corrected alpha value for the tests conducted above, all results that were considered significant before remain significant because they are all less than alpha=.00556; average age differed between all headache types except for “aura” and “mixed”, while average airquality differed between all headache types.</p>
<p>*It is important to note that though we found significant differences in the means among headache types, the assumptions were not all initially met. Therefore, the interpretations of these results are not necessarily reliable. For example, because the covariances were not found to be homogenous across groups, the mean differeneces could be due to inconsistent variance and not necessarily significant differences due to group type.</p>
<p>###Randomization Test
A randomization test was performed to simulate the paired t-test in a different way. This time, we focused on airquality and presence of headache to see if airquality differed at times when someone experienced a headache as opposed to when they did not experience a headache. These results could lead to studies that determine if airquality has an effect on headache onset.</p>
<p>First, the mean differences in airquality for the different headache responses were calculated. Then, responses of air quality were randomly assigned to headache presence and a <strong>null distribution</strong> was created.</p>
<pre class="r"><code>real &lt;- (mean(headache[headache$headache==&quot;yes&quot;,]$airq) - 
           mean(headache[headache$headache==&quot;no&quot;,]$airq))
real</code></pre>
<pre><code>## [1] 0.2849134</code></pre>
<pre class="r"><code>random &lt;- vector()
for(i in 1:5000){
  mixed &lt;- data.frame(airq=sample(headache$airq), presence=headache$headache)
  random[i] &lt;- (mean(mixed[mixed$presence==&quot;yes&quot;,]$airq) -
                  mean(mixed[mixed$presence==&quot;no&quot;,]$airq))}
{hist(random, main=&quot;Null Distribution&quot;, xlab=&quot;Difference in Airquality&quot;); 
  abline(v = 0.2849134, col=&quot;red&quot;); abline(v = -0.2849134, col=&quot;red&quot;)}</code></pre>
<p><img src="/project2final_files/figure-html/unnamed-chunk-9-1.png" width="768" style="display: block; margin: auto;" /></p>
<p>From the created null distribution, the hypotheses were tested by comparing the actual mean difference to the null distribution.</p>
<ul>
<li><p>Ho: Airquality does not differ significantly for days that headaches were experienced versus days that headaches were not experienced.</p></li>
<li><p>HA: Airquality differs significantly for days that headaches were experienced versus days that headaches were not experienced.</p></li>
</ul>
<p>The p-value was then calculated. This value tells the probability that the real mean difference is observed under the null distribution which assumes no association between airquality and headache presence.</p>
<pre class="r"><code>mean(random &gt; 0.2849134 | random &lt; -0.2849134)</code></pre>
<pre><code>## [1] 0.357</code></pre>
<p>The p-value was calculated to be 0.3498, which means there is almost a 35% chance that we would observe the real mean difference of air quality when there is no association between air quality and headache presence. This value is much larger than alpha=.05, therefore we fail to reject the null hypothesis and must assume that airquality does not differ significantly for days that headaches were experienced versus days that headaches were not experienced.</p>
<p>###Linear Regression
A linear regression was run to determine the effects of sex, age, and their interaction on the proportion of days that a participant experienced a headache. Predicting the occurance of a headache from age and sex might help see if certain people are more likely to experience headaches than others. In order to do this, a new variable called “prop_head” was created that represented the proportion of days in the study that the individual experienced a headache. The variable of “age” was also mean centered, represented by “age_c”. Then, the regression was run with these new variables.</p>
<pre class="r"><code>headache2 &lt;- headache %&gt;% select(id, age, sex, headache) %&gt;% 
  group_by(id) %&gt;% mutate(prop_head=mean(headache==&quot;yes&quot;)) %&gt;%
  select(-headache) %&gt;% distinct()
headache2$age_c &lt;- headache2$age - mean(headache2$age)

fit1 &lt;- lm(prop_head~age_c+sex+age_c*sex, data=headache2)
summary(fit1)</code></pre>
<pre><code>##
## Call:
## lm(formula = prop_head ~ age_c + sex + age_c * sex, data
= headache2)
##
## Residuals:
## Min 1Q Median 3Q Max
## -0.67929 -0.19286 0.03694 0.21243 0.39613
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 0.646629 0.025216 25.643 &lt;2e-16 ***
## age_c -0.002155 0.002263 -0.952 0.343
## sexmale -0.011201 0.066021 -0.170 0.866
## age_c:sexmale -0.005369 0.005458 -0.984 0.327
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 0.2679 on 129 degrees of
freedom
## Multiple R-squared: 0.02575, Adjusted R-squared:
0.003097
## F-statistic: 1.137 on 3 and 129 DF, p-value: 0.3368</code></pre>
<p>The summary of the linear regression reveals the coefficients, which can be interpreted as: “intercept” shows that for a female of average age, the proportion of days that headaches are experienced is predicted to be .646629; “age_c” states that for every 1 year age increase, the predicted proportion of headache days decreases by .002155; “sexmale” shows that for a person of average age, their proportion of headache days is predited to decrease by .011201 if they are male; “age_c:sexmale” shows that for males, a 1 year increase in age decreases the predicted proportion of headache days by .005369 more than for females.</p>
<p>This regression can be visualized by:</p>
<pre class="r"><code>ggplot(fit1, aes(age_c, prop_head, color=sex)) + geom_point() + 
  geom_smooth(method=&#39;lm&#39;, se=F) + 
  ggtitle(&quot;Proportion of Headache Days by Age and Sex&quot;)</code></pre>
<p><img src="/project2final_files/figure-html/unnamed-chunk-12-1.png" width="768" style="display: block; margin: auto;" /></p>
<p>Going back, the assumptions of linearity, normality, and homoskedasticity need to be checked prior to interpreting these results with any confidence.</p>
<ul>
<li><strong>Linearity</strong>:</li>
</ul>
<pre class="r"><code>ggplot(headache2, aes(age_c, prop_head)) + geom_point() + 
  ggtitle(&quot;Proportion of Headache Days by Age&quot;)</code></pre>
<p><img src="/project2final_files/figure-html/unnamed-chunk-13-1.png" width="768" style="display: block; margin: auto;" />
The linearity assumption is met, as there is no evidence of curves in the scatterplot of age vs proportion of headaches. <span class="math inline">\(\checkmark\)</span></p>
<ul>
<li><p><strong>Normality</strong>: The Shapiro-Wilk test was conducted to test the assumption of normality.</p>
<ul>
<li>Ho: The distribution is normal</li>
<li>HA: The distribution is not normal</li>
</ul></li>
</ul>
<pre class="r"><code>resids &lt;- fit1$residuals
shapiro.test(resids)</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  resids
## W = 0.95246, p-value = 0.0001462</code></pre>
<p>The results of the Shapiro-Wilk test show that p&lt;.001, so we reject the null hypothesis and assume that the distribution is not normal. Therefore, the assumption of normality is not passed.</p>
<ul>
<li><strong>Homodskedasticity</strong>:</li>
</ul>
<pre class="r"><code>fitvals &lt;- fit1$fitted.values
ggplot() + geom_point(aes(fitvals, resids)) + geom_hline(yintercept=0)</code></pre>
<p><img src="/project2final_files/figure-html/unnamed-chunk-15-1.png" width="768" style="display: block; margin: auto;" />
Though the variance of the residuals does not necessarily look equal along the entirety of the line, there is no obvious fanning of the points. Therefore, the assumption of homoskedasticity is met. <span class="math inline">\(\checkmark\)</span></p>
<p>Even though the assumption of homoskedasticity was met, the regression was recomputed with <strong>robust standard errors</strong>:</p>
<pre class="r"><code>library(sandwich)
library(lmtest)
coeftest(fit1, vcov=vcovHC(fit1))</code></pre>
<pre><code>##
## t test of coefficients:
##
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 0.6466287 0.0261586 24.7195 &lt;2e-16 ***
## age_c -0.0021548 0.0023850 -0.9035 0.3680
## sexmale -0.0112008 0.0631699 -0.1773 0.8595
## age_c:sexmale -0.0053685 0.0062781 -0.8551 0.3941
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<p>After recomputing with robust standard errors, there was not much change seen in the regression results. The standard errors increased slightly (except for “sexmale” that saw a slight decrease), and the p-values followed this trend with a slight increase (except for “sexmale” which slightly decreased). All p-values were much greater than .001, which means they are not significant predictors for proportion of headache days. Along with this, the coefficients remained relatively unchanged as well. Looking at the <strong>R-squared value</strong>, we see that the proportion of variation in the response variable that is explained by the overall model is only .003097. This is an extremely low proportion, signifying a weak model.</p>
<p>###Bootstrapped Standard Errors
Because the normality assumption was not passed, the same regressin was run again with bootstrapped standard errors:</p>
<pre class="r"><code>headache2 &lt;- headache2 %&gt;% ungroup() %&gt;% select(-id)

set.seed(1234)
samp_dist &lt;- replicate(5000, {
boot &lt;- sample_frac(headache2, replace=T)
fit2 &lt;- lm(prop_head~age_c*sex, data=boot)
coef(fit2)
})

samp_dist %&gt;% t %&gt;% as.data.frame %&gt;% summarize_all(sd)</code></pre>
<pre><code>##   (Intercept)       age_c    sexmale age_c:sexmale
## 1  0.02563543 0.002345111 0.05633295   0.005252499</code></pre>
<p>With bootstrapping the standard errors, the standard errors for all variables decreased very slightly, though these changes are almost negligable amounts. The change observed is the same for both the original model and the robust standard error model, as they both had relatively the same values. Because all of the standard errors slightly decreased, this means all of the p-values should also slightly decrease from their values in the original model.</p>
<p>###Logistic Regression
Next, a logistic regression was run to determine how days since onset of treatment and whether the medication is being continued, reduced, or discontinued can predict whether the patient had a headache or not. This might be important in seeing how the length of time that treatment was administered or the level of the treatment can predict the response of headache occurances in patients.
First, the “headache” variable was converted into a binary. Then, the regression was run.</p>
<pre class="r"><code>headache4 &lt;- headache %&gt;% mutate(headache_occur=ifelse(headache==&quot;yes&quot;,1,0)) %&gt;% 
  select(headache_occur, time, medication)
headache4$medication &lt;- factor(headache4$medication, ordered = FALSE )
headache4$medication &lt;- relevel(headache4$medication, ref=&quot;none&quot;)
fit3 &lt;- glm(headache_occur~time+medication, data=headache4, family=&quot;binomial&quot;)
coeftest(fit3)</code></pre>
<pre><code>##
## z test of coefficients:
##
## Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept) -0.1456010 0.0778190 -1.8710 0.061342 .
## time -0.0052268 0.0015956 -3.2757 0.001054 **
## medicationcontinuing 0.8416751 0.0846877 9.9386 &lt;
2.2e-16 ***
## medicationreduced 1.5100027 0.1057633 14.2772 &lt; 2.2e-16
***
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>coeftest(fit3) %&gt;% exp</code></pre>
<pre><code>##
## z test of coefficients:
##
## Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept) 0.86450 1.08093 1.5400e-01 1.063
## time 0.99479 1.00160 3.7800e-02 1.001
## medicationcontinuing 2.32025 1.08838 2.0714e+04 1.000
## medicationreduced 4.52674 1.11156 1.5867e+06 1.000</code></pre>
<p>The logistic regression resulted in the following coefficients: the “intercept” coefficient says that for someone who is experiencing at 0 days of treatment who is in the “none” group of treatment, the odds of experiencing a headache is .86450; the “time” coefficient says that for every 1 day increase in time, their odds of experiencing a headache decreases and is .99479 times the odds for someone on day 0 of treatment in the “none” group; the “medicationcontinuing” coefficient says that for someone who will be continuing medication, their odds of experiencing a headache increases and is 2.32025 times the odds for someone who is not getting treatment; the “medicationreduced” coefficient says that for someone who has reduced medication, their odds of experiencing a headache increases and is 4.52674 times higher than someone who is continuing treatment.</p>
<p>A <strong>confusion matrix</strong>, comparing the true headache occurance versus the predicted headache occurance, can be shown by:</p>
<pre class="r"><code>prob &lt;- predict(fit3, type = &quot;response&quot;)
pred &lt;- ifelse(prob &gt; 0.5, 1, 0)
table(prediction = pred, truth = headache4$headache_occur) %&gt;% addmargins</code></pre>
<pre><code>##           truth
## prediction    0    1  Sum
##        0    440  343  783
##        1   1046 2323 3369
##        Sum 1486 2666 4152</code></pre>
<p>Based on this confusion matrix, the model predicted 2323 true positives, 440 true negatives, 343 false negatives, and 1046 false positives. The extremely high false positive rate signifies that this model overpredicts headache occurance, when in reality a lot of these patients did not experience headaches. This can be further analyzed through:</p>
<pre class="r"><code>#accuracy:
(440+2323)/4152</code></pre>
<pre><code>## [1] 0.6654624</code></pre>
<pre class="r"><code>#sensitivity(TPR):
(2323)/2666</code></pre>
<pre><code>## [1] 0.8713428</code></pre>
<pre class="r"><code>#specificity(TNR):
(440)/1486</code></pre>
<pre><code>## [1] 0.2960969</code></pre>
<pre class="r"><code>#Recall(PPV):
(2323)/3369</code></pre>
<pre><code>## [1] 0.6895221</code></pre>
<p>The <strong>accuracy</strong> rate, or the proportion of predictions that correctly depicted reality, is fairly high at .6654624. The <strong>sensitivity</strong>, or the proportion of headache occurances that were correctly predicted to be headache occurances, is also pretty high at .8713428. However, the <strong>specificity</strong>, or the proportion of non-headache occurances correctly classified as non-headache occurances, was low at only .2960969. The <strong>recall</strong>, or proportion of the classified headache occurances that actually were headache occurances, was a fair proportion at .6895221. Though the model is not very good at predicting with specificity, it is much stronger at predicting with sensitivity. These strengths and weaknesses balance out when we look at the average overall accuracy (we see the trade-offs!).</p>
<p>The <strong>density of log-odds</strong> (logit) by headache occurance can be shown by:</p>
<pre class="r"><code>headache4$logit &lt;- predict(fit3, type=&quot;link&quot;)
headache4 %&gt;% ggplot(aes(logit, fill=factor(headache_occur))) +
  geom_density(alpha=.3) + geom_vline(xintercept=0, color=&#39;red&#39;) +
  labs(fill=&quot;headache&quot;)</code></pre>
<p><img src="/project2final_files/figure-html/unnamed-chunk-21-1.png" width="768" style="display: block; margin: auto;" />
From this plot, the rates described above are illustrated. The high sensitivity is demonstrated by the high blue peaks above the logit=0 line, as this indicates true headache occurances that were predicted to be headache occurances. The low specificity is shown by the low pink peak below the logit=0 line, as this indicates that not many of the true non-headache occurances were classified as such. The average value for recall is seen by the fact that though there are a lot of correctly classified headache occurances (blue peaks to the right of the logit=0 line), there is still a significant number of non-headache occurances that were classified as headaches (pink peaks to the right of the logit=0 line). The grey “overlapped density” areas represent logit values where both true headache occurances and non-headache occurances happen, therefore areas where logit is not a good predictor to differentiate between the two headache groups.</p>
<p>Another way to represent these rates is with an <strong>ROC curve</strong> and <strong>AUC</strong> calculation:</p>
<pre class="r"><code>library(plotROC)
headache4$prob&lt;-predict(fit3,type=&quot;response&quot;)
ROC &lt;- ggplot(headache4) + geom_roc(aes(d=headache_occur, m=prob), n.cuts=0)
ROC</code></pre>
<p><img src="/project2final_files/figure-html/unnamed-chunk-22-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>calc_auc(ROC)</code></pre>
<pre><code>##   PANEL group       AUC
## 1     1    -1 0.6271121</code></pre>
<p>The ROC curve shows us the relationship between false positives and true positives as we change the cutoff value for the model. Ideally, the true positive rate would stay high even as we increase the false positive rate, resulting in an AUC value of 1. The AUC value we calculated of .6271121 tells us that the model is a poor predictor of headache occurance. This weakness is demonstrated by the shape of the ROC curve, as the true positive rate remains relatively low for a while even as the false positive rate increases. Though the model is poor, it might not be completely useless as the AUC value is above a value of .5, which would mean the model predicts no better than choosing a response at random.</p>
<p><strong>Cross-validation</strong> can be used on this model to see how it can be applied to other data other than that which was used to produce the model:</p>
<pre class="r"><code>set.seed(1234)
k=10

data &lt;- headache4[sample(nrow(headache4)),]
fold &lt;- cut(seq(1:nrow(headache4)), breaks=k, labels=F)
val &lt;- NULL
for(i in 1:k){
  trainset &lt;- data[fold!=i,]
  testset &lt;- data[fold==i,]
  truth &lt;- testset$headache_occur
  fit4 &lt;- glm(headache_occur~medication+time, data=trainset, family=&quot;binomial&quot;)
  prob &lt;- predict(fit4, newdata=testset, type=&quot;response&quot;)
  val &lt;- rbind(val, class_diag(prob, truth))
}
summarize_all(val, mean)</code></pre>
<pre><code>##         acc      sens      spec       ppv       auc
## 1 0.6659546 0.8723044 0.2952242 0.6895378 0.6273299</code></pre>
<p>After a 10-fold cross-validation, the AUC remains about the same at .6265165. The average out-of-sample accuracy is .6652352, while the sensitivity is .8714029 and the recall is .6893232. These values only vary slightly from the full-model values.</p>
<p>###LASSO
Focusing only on Aura and non-Aura headaches (excluding the “mixed” headache patients), a LASSO regression was run to see which variables best predict the type of headache that the patient experiences. These results could tell us what factors best predict a future patient’s probability of having aura headaches as opposed to non-aura headaches.</p>
<pre class="r"><code>library(glmnet)
headache5 &lt;- headache %&gt;% select(-id) %&gt;% filter(hatype!=&quot;Mixed&quot;)
y &lt;- as.matrix(headache5$hatype)
x &lt;- model.matrix(hatype~., data=headache5)[,-1]
head(x)</code></pre>
<pre><code>## time dos age airq medicationnone medicationreduced
headacheyes sexmale
## 1 -11 753 30 9 0 0 1 0
## 2 -10 754 30 7 0 0 1 0
## 3 -9 755 30 10 0 0 1 0
## 4 -8 756 30 13 0 0 1 0
## 5 -7 757 30 18 0 0 1 0
## 6 -6 758 30 19 0 0 1 0</code></pre>
<pre class="r"><code>x &lt;- scale(x)
cv &lt;- cv.glmnet(x, y, family = &quot;binomial&quot;)
lasso &lt;- glmnet(x, y, family = &quot;binomial&quot;, lambda = cv$lambda.1se)
coef(lasso)</code></pre>
<pre><code>## 9 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                            s0
## (Intercept)        0.16129030
## time               .         
## dos                0.29161978
## age                0.21255913
## airq               0.14476652
## medicationnone    -0.03325123
## medicationreduced  0.24532956
## headacheyes       -0.10319022
## sexmale            0.17380451</code></pre>
<p>Based on the LASSO regression, using “lambda.1se” in order to maximize regularization, all variables were retained except for “time”. This means that in order to maximize the strength of the model as a predictor without overfitting to the current data, “time” should be excluded. This can be further analyzed through a <strong>10-fold cross-validation</strong>:</p>
<pre class="r"><code>headache6 &lt;- headache5 %&gt;% select(-time) %&gt;% mutate(hatype=ifelse(hatype==&quot;Aura&quot;,1,0))
set.seed(1234)
k=10
data2 &lt;- headache6 %&gt;% sample_frac
folds2 &lt;- ntile(1:nrow(data2), n=10)
val2 &lt;- NULL
for(i in 1:k){
  trainset2 &lt;- data2[folds2!=i,]
  testset2 &lt;- data2[folds2==i,]
  truth2 &lt;- testset2$hatype
  fit5 &lt;- glm(hatype~., data=trainset2, family=&quot;binomial&quot;)
  prob2 &lt;- predict(fit5, newdata=testset2, type=&quot;response&quot;)
  val2 &lt;- rbind(val2, class_diag(prob2, truth2))
}
val2 %&gt;% summarize_all(mean)</code></pre>
<pre><code>##         acc     sens      spec      ppv      auc
## 1 0.6013763 0.550073 0.6470447 0.573028 0.670824</code></pre>
<p>The out-of-sample accuracy for this regression is .2511389. This is much lower than the accuracy of the previous logistic regression which was .6652352 (note however that we are predicting a difference response here). Though these variables were chosen as the best predictors for the model based on what the model was provided, the variables themselves might still not be significant predictors of headache type in real life and therefore the low accuracy.</p>
<p>###Summary
Overall, these tests analyzed differences between headache occurances and types in different demographics. These tools might be helpful in diagnosing the type of headache or frequency of headaches that someone is prone to based on factors such as age or airquality. The MANOVA, ANOVA, and post-hoc tests found that for all headache types, the average airquality differed significantly while the average age differed significantly for all headache types except for when comparing “mixed” headaches and “aura” headaches. The randomization test focused in on average airquality for when people experienced headaches versus when they did not, and it was found that there was no significant difference between airquality average values during headache occurance versus when a headache was not experienced. The linear regression found that though age and sex were not necessarily significant predictors of proportion of headache days, 1 year increases and being male both predicted decreased proportion of headache days in comparison to females of average age. The logistic regression found that both days since the onset of treatment and the level of treatment administered were both significant predictors of headache occurance! The occurance of a headache was predicted to increase significantly for patients who continued or reduced treament, while the occurance of headache was predicted to decrease with increased treatment time. Further clinical tests could be conducted based on this result to determine if the changes in headache occurance was due to the change in medicine level (if headache occurance had a predicted decrease without treatment because the treatment was detrimental), or if the medicine level was changed due to a change in headache occurance (if headache occurance had a prediced decrease without treatment because headache occurance lowered and therefore treatment was stopped).</p>
<p>Though many of the variables tested did not end up being significant predictors of headache occurance, research that does not support a theory can still be valuable! Further tests can be shaped on a lack of significance, as knowledge that age or aiquality for example do not cause someone to be prone to increased proportions of headaches can be helpful in the development of treatment plans.
…</p>

              <hr>
              <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div>
            </div>
          </div>
          <hr>
        <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div>
        </div>
      </div>
      
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="/js/docs.min.js"></script>
<script src="/js/main.js"></script>

<script src="/js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
